### ISSUE TITLE
It works! 

### ISSUE THREAD

**Issue by rickyosser** [benjaminaigner/avr109-webserial#1]
Thank you for this!

I've waited a year to be able to flash upgrades to my custom application built on a avr109 micro platform.

Thanks again!

/Rickard

**Comment by benjaminaigner** [comment]
@rickyosser 

I'm glad it works for you! If you find something to improve, please open a PR / issue.
A star would be nice and if you are interested in Assistive Technology, have a look at
https://github.com/asterics
https://www.asterics.eu
https://www.asterics-foundation.org

Greetings!
